<?php

declare(strict_types=1);

/** One settings query per request; no runtime DDL or filesystem cache. */
final class SiteSettings
{
    private static ?array $cache = null;
    private static array $images = [];
    private static bool $available = false;
    public const IMAGES = ['logo' => 'logo.svg', 'favicon' => 'favicon.svg', 'og_image' => 'og-logo.svg'];
    public const MAX_BYTES = 2 * 1024 * 1024;
    private const MIME = ['png' => 'image/png', 'jpg' => 'image/jpeg', 'jpeg' => 'image/jpeg', 'webp' => 'image/webp'];

    public static function resetCache(): void
    {
        self::$cache = null;
        self::$images = [];
        self::$available = false;
    }

    public static function all(): array
    {
        if (self::$cache === null) {
            self::$cache = [];
            try {
                foreach (db_all('SELECT `setting_key`, `setting_value` FROM `site_settings`') as $row) {
                    self::$cache[$row['setting_key']] = (string) $row['setting_value'];
                }
                self::$available = true;
            } catch (Throwable $e) {
                // Legacy installations and unavailable databases retain repository branding.
                log_error('Site settings unavailable; using defaults.');
            }
        }
        return self::$cache;
    }

    public static function available(): bool
    {
        self::all();
        return self::$available;
    }

    public static function get(string $key): string
    {
        $defaults = ['name' => (string) Config::get('app.name'), 'description' => (string) Config::get('app.description')];
        return self::all()[$key] ?? $defaults[$key] ?? '';
    }

    /** Only paths generated by this service can ever be served or removed. */
    public static function ownedPath(string $path): bool
    {
        return preg_match('~\Auploads/site/[a-f0-9]{48}\.(?:png|jpg|webp)\z~D', $path) === 1;
    }

    private static function diskPath(string $path): ?string
    {
        if (!self::ownedPath($path)) {
            return null;
        }
        $root = (string) Config::get('app.base_path');
        $dir = realpath($root . '/uploads/site');
        $file = $root . '/' . $path;
        $real = realpath($file);
        if ($dir === false || $real === false || is_link($file) || dirname($real) !== $dir || !is_file($real)) {
            return null;
        }
        return $real;
    }

    /** Also validates persisted values: corrupt/missing files fall back safely. */
    public static function imagePath(string $key): string
    {
        if (!isset(self::IMAGES[$key])) {
            throw new InvalidArgumentException('Unknown branding key');
        }
        if (!isset(self::$images[$key])) {
            $path = self::get($key);
            $disk = self::diskPath($path);
            try {
                if ($disk === null) {
                    throw new InvalidArgumentException('Missing image');
                }
                self::validateImage($disk, basename($path));
                self::$images[$key] = '/' . $path;
            } catch (Throwable $e) {
                self::$images[$key] = '/assets/img/' . self::IMAGES[$key];
            }
        }
        return self::$images[$key];
    }

    /** No SVG, HTML, executable names, traversal, client MIME or client size trust. */
    public static function validateImage(string $tmp, string $name): string
    {
        if ($name === '' || str_contains($name, "\0") || strpbrk($name, '/\\') !== false
            || preg_match('/\.(?:php\d*|phtml|phar|html?|svg)(?:\.|$)/i', $name)) {
            throw new InvalidArgumentException('نام فایل مجاز نیست.');
        }
        $ext = strtolower(pathinfo($name, PATHINFO_EXTENSION));
        $size = is_file($tmp) ? filesize($tmp) : false;
        if (!isset(self::MIME[$ext]) || $size === false || $size < 1 || $size > self::MAX_BYTES) {
            throw new InvalidArgumentException('فقط PNG، JPG، JPEG و WEBP تا ۲ مگابایت مجاز است.');
        }
        $mime = (new finfo(FILEINFO_MIME_TYPE))->file($tmp);
        $image = @getimagesize($tmp);
        if ($mime !== self::MIME[$ext] || !$image || ($image['mime'] ?? '') !== $mime
            || $image[0] < 1 || $image[1] < 1 || $image[0] > 4096 || $image[1] > 4096
            || $image[0] * $image[1] > 12000000) {
            throw new InvalidArgumentException('محتوای تصویر معتبر نیست؛ ابعاد باید حداکثر ۴۰۹۶ پیکسل و ۱۲ میلیون پیکسل باشد.');
        }
        return $ext === 'jpeg' ? 'jpg' : $ext;
    }

    private static function upload(array $file): string
    {
        if (($file['error'] ?? null) !== UPLOAD_ERR_OK || !is_string($file['tmp_name'] ?? null)
            || !is_string($file['name'] ?? null) || !is_uploaded_file($file['tmp_name'])) {
            throw new InvalidArgumentException('آپلود کامل نشد. حجم فایل و محدودیت هاست را بررسی کنید.');
        }
        $ext = self::validateImage($file['tmp_name'], $file['name']);
        $path = 'uploads/site/' . bin2hex(random_bytes(24)) . '.' . $ext;
        $target = (string) Config::get('app.base_path') . '/' . $path;
        // The directory and deny-execution policy are shipped together, never created ad hoc.
        if (!is_file(dirname($target) . '/.htaccess') || !is_writable(dirname($target))) {
            throw new RuntimeException('Branding storage unavailable');
        }
        $handle = @fopen($target, 'x'); // exclusive reservation: cannot overwrite any file
        if ($handle === false) {
            throw new RuntimeException('Cannot reserve branding file');
        }
        fclose($handle);
        if (!move_uploaded_file($file['tmp_name'], $target)) {
            @unlink($target);
            throw new RuntimeException('Cannot store branding file');
        }
        @chmod($target, 0644);
        return $path;
    }

    public static function save(array $input, array $files): void
    {
        $values = [];
        foreach (['name' => 120, 'description' => 500] as $key => $limit) {
            if (!is_string($input[$key] ?? null)) {
                throw new InvalidArgumentException('نام و توضیح سایت معتبر نیست.');
            }
            $values[$key] = trim($input[$key]);
            if (($key === 'name' && $values[$key] === '') || mb_strlen($values[$key], 'UTF-8') > $limit) {
                throw new InvalidArgumentException('نام سایت الزامی و حداکثر ۱۲۰ نویسه؛ توضیح حداکثر ۵۰۰ نویسه است.');
            }
        }
        $created = [];
        $old = [];
        $pdo = db();
        try {
            foreach (self::IMAGES as $key => $fallback) {
                $file = $files[$key] ?? null;
                $remove = ($input['reset_' . $key] ?? '') === '1';
                $hasFile = $file !== null && (!is_array($file) || ($file['error'] ?? null) !== UPLOAD_ERR_NO_FILE);
                if ($remove && $hasFile) {
                    throw new InvalidArgumentException('برای هر تصویر فقط یکی از انتخاب فایل یا بازگردانی پیش‌فرض را انجام دهید.');
                }
                if ($hasFile) {
                    if (!is_array($file)) {
                        throw new InvalidArgumentException('فایل نامعتبر است.');
                    }
                    $values[$key] = self::upload($file);
                    $created[] = $values[$key];
                } elseif ($remove) {
                    $values[$key] = '';
                }
            }
            $pdo->beginTransaction();
            $mysql = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME) === 'mysql';
            foreach ($values as $key => $value) {
                $row = db_one('SELECT `setting_value` FROM `site_settings` WHERE `setting_key` = ?' . ($mysql ? ' FOR UPDATE' : ''), [$key]);
                if (isset(self::IMAGES[$key]) && $row) {
                    $old[] = (string) $row['setting_value'];
                }
                $sql = $mysql
                    ? 'INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES (?, ?) ON DUPLICATE KEY UPDATE `setting_value` = VALUES(`setting_value`)'
                    : 'INSERT INTO `site_settings` (`setting_key`, `setting_value`) VALUES (?, ?) ON CONFLICT(`setting_key`) DO UPDATE SET `setting_value` = excluded.`setting_value`';
                db_run($sql, [$key, $value]);
            }
            $pdo->commit();
        } catch (Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            foreach ($created as $path) {
                self::removeFile($path);
            }
            throw $e;
        }
        self::resetCache();
        foreach ($old as $path) {
            if (!in_array($path, $values, true)) {
                self::removeFile($path);
            }
        }
    }

    private static function removeFile(string $path): void
    {
        $file = self::diskPath($path);
        if ($file !== null) {
            @unlink($file);
        }
    }
}

function site_setting(string $key): string
{
    return SiteSettings::get($key);
}

function site_image(string $key): string
{
    return url(SiteSettings::imagePath($key));
}
